#################
### AUTOSTART ###
#################

exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar & hypridle & swaync & swayosd-server
exec-once = clipse -listen
exec-once = mpvpaper -o "hwdec=auto-safe gpu-context=wayland no-audio loop-file=inf vf=fps=24 vd-lavc-threads=1 --input-ipc-server=/tmp/mpvsocket" ALL ~/.config/images/background/wallpaper_optimized.mp4
exec-once = mpvpaper-stop
exec-once = snappy-switcher --daemon
