background {
  monitor =
  path = ~/.config/images/background/wallpaper.png
}

label {
    monitor =
    position = 0, 24
    text = $USER
    font_size = 32
    font_family = Upheaval Pro
    color = #ffffff
}

input-field {
  monitor =
  position = 0, -24
  size =  288, 48
  fade_on_empty = false

  font_family = Upheaval Pro
  font_color = rgba(255, 255, 255, 1.0)
  dots_size = 0.4
  dots_spacing = 0.1

  placeholder_text = 

  rounding = 16
  outline_thickness = 4
  outer_color =  rgba(255, 255, 255, 1.0)
  inner_color = rgba(0, 0, 0, 0.1)
  check_color = rgba(255, 255, 255, 1.0)
  fail_color = rgba(255, 255, 255, 1.0)
  capslock_color = rgba(255, 255, 255, 1.0)
}
