background {
  monitor =
}

label {
    monitor =
    position = 0, 24
    text = $USER
    font_size = 20
    weight = 500
    font_family = JetBrains Nerd Font Bold
    color = #ffffff
}

input-field {
  monitor =
  position = 0, -32
  size =  288, 48
  fade_on_empty = false

  font_family = JetBrains Nerd Font
  font_color = rgba(255, 255, 255, 1.0)
  dots_size = 0.4
  dots_spacing = 0.1

  placeholder_text = 

  rounding = 16
  outline_thickness = 4
  outer_color =  rgba(255, 255, 255, 1.0)
  inner_color = rgba(0, 0, 0, 0.1)
  check_color = rgba(255, 255, 255, 1.0)
  fail_color = rgba(255, 255, 255, 1.0)
  capslock_color = rgba(255, 255, 255, 1.0)
}

auth {
    pam:enabled = true
    pam:module = hyprlock

    fingerprint:enabled = true
}
