#############
### INPUT ###
#############

gesture = 3, horizontal, workspace

input {
  follow_mouse = 1

  repeat_rate = 40
  repeat_delay = 400  

  kb_options = ctrl:nocaps, altwin:swap_alt_win

  touchpad {
    scroll_factor = 0.2
    clickfinger_behavior = true
    disable_while_typing = true
    natural_scroll = true
  }

  windowrule = match:class (kitty), scroll_touchpad 0.6
}

cursor {
    inactive_timeout = 0.5
}
