# quick reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# enable mouse
set -g mouse on

# change prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

set -gq allow-passthrough all
set -g visual-activity off
set-option -g focus-events on

# pane navigation with vim keybindings
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# resizing pane
bind -r C-h resize-pane -L 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5

# yank with vim keybindings
set -g set-clipboard on
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'wl-copy'

# run claude in a popup window
bind -r C run-shell '\
  SESSION="claude-$(echo "#{pane_current_path}" | md5sum | cut -c1-8)"; \
  tmux has-session -t "$SESSION" 2>/dev/null || \
  tmux new-session -d -s "$SESSION" -c "#{pane_current_path}" "claude"; \
  tmux set-option -t "$SESSION" status off; \
  tmux display-popup -d "#{pane_current_path}" -w90% -h90% -E "tmux attach-session -t $SESSION"'

# run codex in a popup window
bind -r O run-shell '\
  SESSION="codex-$(echo "#{pane_current_path}" | md5sum | cut -c1-8)"; \
  tmux has-session -t "$SESSION" 2>/dev/null || \
  tmux new-session -d -s "$SESSION" -c "#{pane_current_path}" "codex"; \
  tmux set-option -t "$SESSION" status off; \
  tmux display-popup -d "#{pane_current_path}" -w90% -h90% -E "tmux attach-session -t $SESSION"'

# split in cwd
bind '"' split-window -v -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'

# start windows and panes at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# status bar
set -g @catppuccin_status_background 'none' # transparent background for status bar
set-option -g status-position top

# theme config
set -ogq @catppuccin_window_status_style 'custom' # basic, rounded, slanted, custom, or none
set -ogq @catppuccin_window_text ' #W #[fg=#313244,bg=default]' # default window name
set -ogq @catppuccin_window_number '#[fg=#7f849c,bg=default]#[fg=#181825,bg=#7f849c] #I ' # default window index
set -ogq @catppuccin_window_current_text ' #W #[fg=#45475c,bg=default]' # current window name
set -ogq @catppuccin_window_current_number '#[fg=#eba0ac,bg=default]#[fg=#1e1e2e,bg=#eba0ac] #I ' # current window index
# block cursor with custom color
set -g default-terminal "tmux-256color"
set -as terminal-features ',xterm-kitty:RGB'
set -g cursor-style block
set -g cursor-colour "#179299"  # Catppuccin peach

run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

# style popup pane
set -g popup-style 'bg=default,fg=#cdd6f4'
set -g popup-style 'bg=default,fg=#cdd6f4'
set -g popup-border-style 'fg=#cba6f7'
set -g popup-border-lines rounded

set -g status-left-length 100
set -g status-left '#[fg=#fab387,bg=default]#[fg=#1e1e2e,bg=#fab387,bold] #S #[fg=#fab387,bg=default] ' # session nae
set -g status-right-length 100
set -g status-right "#[fg=#a6e3a1,bold]#{?client_prefix, PREFIX ,}"
set -g status-interval 1

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
